apps/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    # path('')
]

apps/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
]

conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    # admin stuff
    path('admin/', admin.site.urls),

    # users management
    path('accounts/', include('allauth.urls')),

    # local apps
    path('books/', include('apps.books.urls', namespace='books')),
    path('', include('apps.pages.urls', namespace='')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

apps/books/models.py
from django.contrib.auth import get_user_model
from django.db import models

from decimal import Decimal

from django.db.models import Avg

from .utils import RATE_CHOICES
from .validators import validate_discount

User = get_user_model()


class Book(models.Model):
    """
    Model for book objects
    """
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, db_index=True)
    description = models.TextField(max_length=1255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    available = models.BooleanField(default=True)
    pub_year = models.PositiveSmallIntegerField(
        verbose_name='Publication year'
    )
    discount = models.PositiveSmallIntegerField(
        null=True, blank=True, verbose_name=r'% discount',
        validators=[validate_discount]
    )
    edition_number = models.PositiveSmallIntegerField(
        verbose_name='Edition number'
    )
    added = models.DateField(auto_now_add=True)

    # relations
    genre = models.ForeignKey(
        'Genre', on_delete=models.CASCADE, related_name='books'
    )
    authors = models.ManyToManyField('Author', related_name='books')
    series = models.ForeignKey(
        'BookSeries', on_delete=models.CASCADE,
        related_name='books', null=True, blank=True
    )

    def __str__(self):
        return self.title

    def get_rating(self):
        """
        this method returns rating by calculation average value of all
        related reviews rate
        """
        return self.reviews.aggregate(Avg('rate'))

    def get_price_with_discount(self):
        """
        this method calculates price of the book, taking into account
        the discount if there is no discount - returns original price
        """
        if self.discount:
            final_price = Decimal(self.price) * \
                    (1 - Decimal(self.discount) / 100)
            return str(final_price)
        else:
            return str(self.price)


class Genre(models.Model):
    """
    model for book genres
    """
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, db_index=True)

    def __str__(self):
        return self.title

    def get_related_books_num(self):
        """this method returns number of books related to this genre"""
        return len(self.books.all())


class Author(models.Model):
    """
    Model for book authors
    """
    first_name = models.CharField(max_length=255, verbose_name='First name')
    surname = models.CharField(max_length=255, verbose_name='Surname')
    patronymic = models.CharField(max_length=255, verbose_name='Patronymic')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return f'Author: {self.first_name} {self.surname}'

    def get_related_books_num(self):
        """
        this method returns number of books related to this author
        """
        return len(self.books.all())


class BookReview(models.Model):
    """
    Model for book reviews. It is essentially a link table between the book and
    the user models, implementing a many-to-many relationship between them
    """
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name='reviews'
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='book_reviews'
    )

    rate = models.PositiveSmallIntegerField(choices=RATE_CHOICES)
    body = models.TextField(max_length=1255, blank=True, null=True)

    class Meta:
        # setting that one user can make only one review for each book
        unique_together = ['book', 'user']

    def __str__(self):
        return f'Review for book {self.book.slug} by user {self.user.username}'


class BookSeries(models.Model):
    """
    Model for a series of books (like Harry Potter, etc)
    """
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title


class BookImage(models.Model):
    """
    Model for book images
    """
    book = models.ForeignKey(
        Book, on_delete=models.CASCADE, related_name='image_gallery'
    )
    image = models.ImageField(upload_to='%Y/%m/%d/')

apps/pages/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

apps/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

apps/books/views.py
from django.shortcuts import render

# Create your views here.

apps/pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = 'pages/home.html'


class AboutPageView(TemplateView):
    template_name = 'pages/about.html'

templates/pages/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>{% block title %}Bookstore{% endblock title %}</title>
</head>
<body>
{% include 'pages/layouts/navbar.html' %}

<div class="container">
    {% block content %}
    {% endblock content %}
</div>
{% if user.is_staff %}
<div class="admin-panel">
    <a href="/admin/" class="btn btn-primary">Admin</a>
</div>
{% endif %}

</body>
</html>

templates/pages/about.html
{% extends 'pages/_base.html' %}

{% block title %} About page| {{ block.super }} {% endblock title %}

{% block content %}
    <h4>Hello, this is about page!</h4>
{% endblock content %}

templates/pages/home.html
{% extends 'pages/_base.html' %}

{% block title %}Home{% endblock title %}
{% block content %}
    <h1>Homepage</h1>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
    {% else %}
        <a href="{% url 'account_login' %}">Please login!</a>
    {% endif %}
{% endblock content %}

templates/pages/layouts/categories_sidebar.html
<div class="col-lg-3">

    <h1 class="my-4">Shop Name</h1>
    <div class="list-group">
        <a href="#" class="list-group-item">Category 1</a>
        <a href="#" class="list-group-item">Category 2</a>
        <a href="#" class="list-group-item">Category 3</a>
    </div>

</div>

templates/pages/layouts/navbar.html
<header>
    <!-- Fixed navbar -->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4
mb-3 bg-white border-bottom shadow-sm">
        <a href="{% url 'pages:home' %}" class="navbar-brand my-0 mr-md-auto
font-weight-normal">Bookstore</a>
        <nav class="my-2 my-md-0 mr-md-3">
            <a class="p-2 text-dark" href="{% url 'pages:about' %}">About</a>
            {% if user.is_authenticated %}
                <a class="p-2 text-dark" href="{% url 'account_logout' %}">Log Out</a>
            {% else %}
                <a class="p-2 text-dark" href="{% url 'account_login' %}">Log In</a>
                <a class="btn btn-outline-primary"
                   href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}
        </nav>
    </div>
</header>